### ISSUE TITLE
Code on github more current than on PyPI

### ISSUE THREAD

**Issue by buekera** [truenas/py-SMART#20]
I installed pySMART with `pip install pySMART` and ran into an error:

```
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from pySMART import Device
  File "/home/buekera/PycharmProjects/smartnoti/venv/lib/python3.6/site-packages/pySMART/__init__.py", line 102, in <module>
    from .device import Device
  File "/home/buekera/PycharmProjects/smartnoti/venv/lib/python3.6/site-packages/pySMART/device.py", line 33, in <module>
    from .utils import *
  File "/home/buekera/PycharmProjects/smartnoti/venv/lib/python3.6/site-packages/pySMART/utils.py", line 125, in <module>
    for line in _stdout.split('\n'):
TypeError: a bytes-like object is required, not 'str'
```

When I compared the code from this repo with the code contained within the installed package I saw that it's different.

I cloned the repo and added it to my project and the error was gone. I used python 3.6.5 to install the package, maybe there is the issue?

**Comment by oxc** [comment]
I don't think the project on pypi is backed by this github project. Instead that's the pypi page of the original pySMART project this fork is based upon. 
Unfortunately this fact is not reflected very well in the documentation of this github project (especially since it still lists the `pip install pySMART` command).

**Comment by MichaIng** [comment]
Latest version comes from this fork now and links on PyPI have been updated: https://pypi.org/project/pySMART/

**Comment by jantman** [comment]
It seems like this is still an issue?

I have an Arch Linux system with 

Running pySMART 1.0 from PyPI gives me no test results:

```python
>>> dev.update()
>>> dev.tests
>>> dev.messages
[]
>>> dev.serial
'WD-WCC6Y1VUYLZX'
>>> dev.all_selftests()
'No self-tests have been logged for this device.'
```

Installing from github (``pip install -e 'git+https://github.com/freenas/py-SMART.git#egg=pySMART'``), however, gives shows me the tests for the same device:

```python
>>> dev.tests
[<SMART Self-test [Short offline|Completed without error] hrs:5421 LBA:->, <SMART Self-test [Short offline|Completed without error] hrs:5415 LBA:->, <SMART Self-test [Short offline|Completed without error] hrs:5391 LBA:->, <SMART Self-test [Short offline|Completed without error] hrs:5367 LBA:->, <SMART Self-test [Short offline|Completed without error] hrs:5343 LBA:->, <SMART Self-test [Short offline|Completed without error] hrs:5319 LBA:->, <SMART Self-test [Short offline|Completed without error] hrs:5295 LBA:->, <SMART Self-test [Short offline|Completed without error] hrs:5271 LBA:->, <SMART Self-test [Short offline|Completed without error] hrs:5248 LBA:->, <SMART Self-test [Short offline|Completed without error] hrs:5224 LBA:->, <SMART Self-test [Short offline|Completed without error] hrs:5200 LBA:->, <SMART Self-test [Short offline|Completed without error] hrs:5176 LBA:->, <SMART Self-test [Short offline|Completed without error] hrs:5152 LBA:->, <SMART Self-test [Short offline|Completed without error] hrs:5128 LBA:->, <SMART Self-test [Short offline|Completed without error] hrs:5104 LBA:->, <SMART Self-test [Short offline|Completed without error] hrs:5080 LBA:->, <SMART Self-test [Short offline|Completed without error] hrs:5058 LBA:->, <SMART Self-test [Short offline|Completed without error] hrs:5034 LBA:->, <SMART Self-test [Short offline|Completed without error] hrs:5010 LBA:->, <SMART Self-test [Short offline|Completed without error] hrs:4986 LBA:->, <SMART Self-test [Short offline|Completed without error] hrs:4962 LBA:->]
>>> dev.messages
[]
>>> dev.all_selftests()
['ID Test_Description Status                        Left Hours  1st_Error@LBA    ', '# 1 Short offline    Completed without error       00%  5421   -                ', '# 2 Short offline    Completed without error       00%  5415   -                ', '# 3 Short offline    Completed without error       00%  5391   -                ', '# 4 Short offline    Completed without error       00%  5367   -                ', '# 5 Short offline    Completed without error       00%  5343   -                ', '# 6 Short offline    Completed without error       00%  5319   -                ', '# 7 Short offline    Completed without error       00%  5295   -                ', '# 8 Short offline    Completed without error       00%  5271   -                ', '# 9 Short offline    Completed without error       00%  5248   -                ', '#10 Short offline    Completed without error       00%  5224   -                ', '#11 Short offline    Completed without error       00%  5200   -                ', '#12 Short offline    Completed without error       00%  5176   -                ', '#13 Short offline    Completed without error       00%  5152   -                ', '#14 Short offline    Completed without error       00%  5128   -                ', '#15 Short offline    Completed without error       00%  5104   -                ', '#16 Short offline    Completed without error       00%  5080   -                ', '#17 Short offline    Completed without error       00%  5058   -                ', '#18 Short offline    Completed without error       00%  5034   -                ', '#19 Short offline    Completed without error       00%  5010   -                ', '#20 Short offline    Completed without error       00%  4986   -                ', '#21 Short offline    Completed without error       00%  4962   -                ']
>>> 
```

**Comment by MichaIng** [comment]
While the latest PyPI release is based on this repo, the last upload has been done summer last year. Especially to fix Python 3.8 support (#31) and probably your issue, an upload of the current version is urgently required.

**Comment by ralequi** [comment]
I've become an official maintainer of the github/pypi repo.
New release is going to be pushed today.

**Comment by MichaIng** [comment]
That is awesome news. Great to hear and makes the decision obsolete whether to use your fork (many thanks for that btw 👍) or not 🙂.
