### ISSUE TITLE
ValueError: could not convert string to float in device.py

### ISSUE THREAD

**Issue by ulmitov** [truenas/py-SMART#51]
Python 3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

import pySMART
devlist = pySMART.DeviceList()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/pySMART/device_list.py", line 63, in __init__
    self._initialize()
  File "/usr/local/lib/python3.8/dist-packages/pySMART/device_list.py", line 110, in _initialize
    Device(name, interface=interface, smartctl=self.smartctl))
  File "/usr/local/lib/python3.8/dist-packages/pySMART/device.py", line 283, in __init__
    self.update()
  File "/usr/local/lib/python3.8/dist-packages/pySMART/device.py", line 1119, in update
    self.diagnostics._Reads_GB = float(line_[6])
ValueError: could not convert string to float: '38279,982'

**Comment by ralequi** [comment]
Please, provide the following output to be included in tests:

```bash
echo $LANG
smartctl --scan-open
smartctl --all /dev/sda # or whatever your disk path is
```

Thank you

**Comment by ralequi** [comment]
Bug confirmed. It seems it just appears on scsi.

I need the output of `smartctl -d scsi -l background /dev/sdc` to fully include this data into the tests

**Comment by ralequi** [comment]
Thank you @ulmitov .
Fixes have been pushed
