### ISSUE TITLE
utils.configure_trace_logging(), smartctl.py logger initialization race

### ISSUE THREAD

**Issue by henryptung** [truenas/py-SMART#91]
`utils.configure_trace_logging()` executes too late to intercept the static logger created in `smartctl.py`, resulting in the following error:

```
[htung@HPT-Server /etc ]$ python                                                     
Python 3.12.7 (main, Oct  1 2024, 11:15:50) [GCC 14.2.1 20240910] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pySMART import SMARTCTL
>>> SMARTCTL.scan()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.12/site-packages/pySMART/smartctl.py", line 191, in scan
    return self.generic_call(['--scan-open'])[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pySMART/smartctl.py", line 116, in generic_call
    logger.trace("Executing the following cmd: {0}".format(popen_list))
    ^^^^^^^^^^^^
AttributeError: 'Logger' object has no attribute 'trace'
>>> 
```

- smartctl version: Not relevant (didn't make it to execution)
- pySMART version: 1.4.0 (1.4.0-1 via Arch User Repository)

Currently, this is causing the Glances smart plugin to fail on my Arch server. Not sure what a good fix is here, though relying on globals initialization order seems a little fragile IMO, as well as relying on `logging.setLoggerClass()` to configure global state (what if another library wants to do the same?).

**Comment by psapezhka** [comment]
+1

**Comment by danpodeanu** [comment]
I can reproduce this - py-SMART is broken at the moment.

```
root@dev:~# python3 -m venv test-pysmart

root@dev:~# cd test-pysmart

root@dev:~/test-pysmart# bin/pip3 install pysmart
Collecting pysmart
  Using cached pySMART-1.4.0-py3-none-any.whl.metadata (9.6 kB)
Collecting chardet (from pysmart)
  Using cached chardet-5.2.0-py3-none-any.whl.metadata (3.4 kB)
Collecting humanfriendly (from pysmart)
  Using cached humanfriendly-10.0-py2.py3-none-any.whl.metadata (9.2 kB)
Using cached pySMART-1.4.0-py3-none-any.whl (64 kB)
Using cached chardet-5.2.0-py3-none-any.whl (199 kB)
Using cached humanfriendly-10.0-py2.py3-none-any.whl (86 kB)
Installing collected packages: humanfriendly, chardet, pysmart
Successfully installed chardet-5.2.0 humanfriendly-10.0 pysmart-1.4.0

root@dev:~/test-pysmart# bin/python3
Python 3.12.3 (main, Nov  6 2024, 18:32:19) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pySMART import Device
>>> sda = Device('/dev/sda')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/test-pysmart/lib/python3.12/site-packages/pySMART/device.py", line 260, in __init__
    raw, returncode = self.smartctl.generic_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/test-pysmart/lib/python3.12/site-packages/pySMART/smartctl.py", line 116, in generic_call
    logger.trace("Executing the following cmd: {0}".format(popen_list))
    ^^^^^^^^^^^^
AttributeError: 'Logger' object has no attribute 'trace'
```

This is a temporary fix:

```
--- lib/python3.12/site-packages/pySMART/smartctl.py.original	2025-01-05 06:19:08.087066052 +0000
+++ lib/python3.12/site-packages/pySMART/smartctl.py	2025-01-05 06:19:13.805090190 +0000
@@ -113,7 +113,7 @@
 
         popen_list.extend(params)
 
-        logger.trace("Executing the following cmd: {0}".format(popen_list))
+        logger.debug("Executing the following cmd: {0}".format(popen_list))
 
         return self._exec(popen_list)
```

**Comment by f18m** [comment]
I'm getting the same error... reverting to previous pySMART release...

**Comment by ralequi** [comment]
Sorry guys, I was on vacation 3 weeks and this first week was too hard to alloc time for this.
Didn't notice this bug on my tests, very sorry for the delay, I'll try to fix this today.
Thanks for reporting it!

**Comment by ralequi** [comment]
https://github.com/truenas/py-SMART/releases/tag/v1.4.1
https://pypi.org/project/pySMART/1.4.1/

I think everything should work now.
This was a quick fix, I'll clean it up sometime soon, but at least it shouldn't crash anymore.

When you confirm everything is ok, I'll close this,
Thank you all!

**Comment by f18m** [comment]
Thanks @ralequi . I just tested version 1.4.1 and it works for me!
